/*KAZe/Meldac*/

#define ramSize 65536

#define VER_STD	0

enum EventTypes
{
	EVENT_UNKNOWN0 = 1,
	EVENT_NOP,
	EVENT_REST,
	EVENT_ECHO_DELAY,
	EVENT_ECHO_FEEDBACK,
	EVENT_ECHO_FIR,
	EVENT_ASDR_MODE,
	EVENT_GAIN_ENV_MODE,
	EVENT_TIE_STATE,
	EVENT_NOISE_ON,
	EVENT_NOISE_OFF,
	EVENT_PROGCHANGE_FROM_TABLE,
	EVENT_PROGTABLE_WRITE_2,
	EVENT_ECHO_VOLUME_PAN,
	EVENT_ECHO_VOLUME,
	EVENT_ECHO_ON,
	EVENT_ECHO_OFF,
	EVENT_PROGTABLE_WRITE_3,
	EVENT_MASTER_VOLUME_PAN,
	EVENT_MASTER_VOLUME,
	EVENT_PAN,
	EVENT_VOLUME,
	EVENT_NOTE_ON_DELAY,
	EVENT_REPEAT_START,
	EVENT_REPEAT_END,
	EVENT_SLUR_OFF,
	EVENT_SLUR_ON,
	EVENT_TRANSPOSE,
	EVENT_TEMPO,
	EVENT_MASTER_VOLUME_FADE,
	EVENT_CALL,
	EVENT_JUMP,
	EVENT_RETURN,
	EVENT_END,

};

unsigned int STATUS_NOTE_MIN;
unsigned int STATUS_NOTE_MAX;

unsigned int EventMap[256];