#define VER_STD			0x00		/*Standard format*/
#define VER_SMW			0x01		/*Early version (Super Mario World/Pilotwings)*/
#define VER_BUBSY		0x02		/*Chip Level Designs (earlier)*/
#define VER_SUPERMAN	0x03		/*Chip Level Designs (later)*/
#define VER_HUMAN		0x04		/*Human*/
#define VER_DATAEAST	0x05		/*Data East*/
#define VER_KONAMI		0x06		/*Konami*/
#define VER_SSR			0x07		/*Sunset Riders*/
#define VER_SFA2		0x08		/*Street Fighter Alpha 2*/
#define VER_MARV		0x09		/*Akito Nakatsuka*/
#define VER_FE3			0x0A		/*Intelligent Systems (earlier)*/
#define VER_FE4			0x0B		/*Intelligent Systems (later type 1)*/
#define VER_TA			0x0C		/*Intelligent Systems (later type 2)*/
#define VER_SUNSOFT		0x0D		/*Sunsoft*/
#define VER_YSFR		0x0E		/*TOSE (later type 1)*/
#define VER_SBL3		0x0F		/*TOSE (later type 2)*/
#define VER_LEMMINGS	0x10		/*Lemmings*/
#define VER_QUINTET		0x11		/*Quintet*/
#define VER_TAITO		0x12		/*Kazuo Sawa/Taito/C-lab*/
#define VER_RC3			0x13		/*Ocean (common)*/
#define VER_JPARK		0x14		/*Ocean (Jurassic Park)*/
#define VER_FFS			0x15		/*Monolith*/
#define VER_SFB			0x16		/*Argonaut Software (early 1)*/
#define VER_KINGARTHUR	0x17		/*Argonaut Software (early 2)*/
#define VER_VORTEX		0x18		/*Argonaut Software (later)*/
#define VER_JAM			0x19		/*Japan Art Media*/
#define VER_ACC			0x1A		/*Advance Communication*/
#define VER_KOEI		0x1B		/*KOEI (later)*/
#define VER_AISYSTEM	0x1C		/*Aisystem Tokyo*/
#define VER_KS			0x1D		/*Kennosuke Suemura*/
#define VER_NEXUS		0x1E		/*Nexus Interact*/
#define VER_OUTBACK		0x1F		/*Daft/Outback*/
#define VER_HECT		0x20		/*Hect*/
#define VER_DQ6			0x21		/*Dragon Quest 6/3 (Heart Beat)*/
#define VER_OGRE		0x22		/*Ogre Battle*/
#define VER_TO			0x23		/*Tactics Ogre*/
#define VER_CUBE		0x24		/*CUBE*/
#define VER_VIRGIN		0x25		/*Virgin*/
#define VER_CPBRAIN		0x26		/*CP.BRAiN*/
#define VER_HANARI		0x27		/*Hanari Exp*/
#define VER_SADA		0x28		/*Kyouhei Sada (Pure Sound)*/
#define VER_DDW			0x29		/*Doomsday Warrior*/
#define VER_BLCB		0x2A		/*Make Software (early?)*/
#define VER_SAI2		0x2B		/*Make Software (type 1)*/
#define VER_MDH			0x2C		/*Make Software (type 2)*/
#define VER_MIHO		0x2D		/*MIHO (Riverse Kids)*/
#define VER_SDD			0x2E		/*Super Double Dragon*/
#define VER_SNKK		0x2F		/*Shodai Nekketsu Kouha Kunio-kun*/
#define VER_MSQ			0x30		/*MSQ (Hatayama Hatch no Pro Yakyuu News! Jinsei Han)*/
#define VER_7TH			0x31		/*The 7th Saga*/
#define VER_MELFAND		0x32		/*Sting (later)*/
#define VER_FH			0x33		/*Sting (early)*/
#define VER_THG			0x34		/*Sting (later v2)*/
#define VER_F1GP3		0x35		/*F-1 Grand Prix Part 3*/
#define VER_SDF1		0x36		/*SD F-1 Grand Prix*/
#define VER_KDCS		0x37		/*Kiteretsu Daihyakka*/
#define VER_BETOP		0x38		/*Betop (I'Max)*/

enum EventTypes
	/*Based on names from VGMTrans*/
{
	EVENT_UNKNOWN0 = 1,
	EVENT_UNKNOWN1,
	EVENT_UNKNOWN2,
	EVENT_UNKNOWN3,
	EVENT_UNKNOWN4,
	EVENT_NOP,
	EVENT_NOP1,
	EVENT_NOP2,
	EVENT_NOP3,
	EVENT_END,
	EVENT_NOTE_LEN,
	EVENT_NOTE,
	EVENT_TIE,
	EVENT_REST,
	EVENT_PERCUSSION_NOTE,
	EVENT_PROG_CHANGE,
	EVENT_PAN,
	EVENT_PAN_FADE,
	EVENT_VIBRATO_ON,
	EVENT_VIBRATO_OFF,
	EVENT_MASTER_VOLUME,
	EVENT_MASTER_VOLUME_FADE,
	EVENT_TEMPO,
	EVENT_TEMPO_FADE,
	EVENT_GLOBAL_TRANSPOSE,
	EVENT_LOCAL_TRANSPOSE,
	EVENT_TREMOLO_ON,
	EVENT_TREMOLO_OFF,
	EVENT_VOLUME,
	EVENT_VOLUME_FADE,
	EVENT_CALL,
	EVENT_VIBRATO_FADE,
	EVENT_PITCH_ENVELOPE_TO,
	EVENT_PITCH_ENVELOPE_FROM,
	EVENT_PITCH_ENVELOPE_OFF,
	EVENT_TUNING,
	EVENT_ECHO_ON,
	EVENT_ECHO_OFF,
	EVENT_ECHO_PARAM,
	EVENT_ECHO_VOLUME,
	EVENT_PITCH_SLIDE,
	EVENT_PERCUSSION_PATCH_BASE,
	EVENT_MUTE,
	EVENT_FAST_FORWARD_ON,
	EVENT_FAST_FORWARD_OFF,
	EVENT_JUMP,
	/*Chip Level Designs*/
	EVENT_CLD_DISTORT_ON,
	EVENT_CLD_DISTORT_OFF,
	/*Data East*/
	EVENT_DE_SUB_COMMAND,
	/*Konami*/
	EVENT_KON_PITCH3,
	EVENT_KON_REPEAT_START,
	EVENT_KON_REPEAT_END,
	EVENT_KON_ECHO_OFF,
	EVENT_KON_ENVELOPE,
	/*Sunsoft Riders*/
	EVENT_SSR_CALL,
	EVENT_SSR_REPEAT,
	EVENT_SSR_RETURN,
	/*Marvelous*/
	EVENT_MARV_ASDR,
	/*Intelligent Systems*/
	EVENT_IS_ECHO_ON,
	EVENT_IS_ECHO_OFF,
	EVENT_IS_LEGATO_ON,
	EVENT_IS_LEGATO_OFF,
	EVENT_IS_CA,
	EVENT_IS_APU_WRITE,
	EVENT_IS_JUMP_CONDITIONAL,
	EVENT_IS_JUMP,
	EVENT_IS_EVENT_F9,
	EVENT_IS_EVENT_FC,
	EVENT_IS_VOICE_DEF,
	EVENT_IS_VOICE_SET,
	EVENT_IS_ASDR,
	EVENT_IS_DUR_GAIN,
	EVENT_IS_DUR,
	EVENT_IS_GAIN,
	EVENT_IS_GAIN_RELEASE,
	EVENT_IS_SUB_COMMAND,
	/*Sunsoft*/
	EVENT_SS_ECHO_ON,
	EVENT_SS_ECHO_OFF,
	EVENT_SS_ASDR,
	EVENT_SS_GLOBAL_SONG_VOLUME,
	/*Quintet*/
	EVENT_QT_ASDR,
	/*TOSE*/
	EVENT_TOSE_APU_WRITE,
	EVENT_TOSE_NOISE,
	/*Ocean*/
	EVENT_OCEAN_GAIN_ON,
	EVENT_OCEAN_GAIN_OFF,
	/*Monolith*/
	EVENT_MONOLITH_DEC_POS,
	EVENT_MONOLITH_GOTO,
	EVENT_MONOLITH_SET_INS_PARAMETER,
	EVENT_MONOLITH_ECHO_OFF,
	/*Argonaut Software*/
	EVENT_ARGONAUT_ASDR,
	EVENT_ARGONAUT_ASDR_ENV,
	EVENT_ARGONAUT_FIR,
	/*Advance Communication*/
	EVENT_ACC_ASDR,
	EVENT_ACC_ASDR_ENV,
	EVENT_ACC_ASDR_ENV_TABLE_1,
	EVENT_ACC_ASDR_ENV_TABLE_2,
	EVENT_ACC_ASDR_ENV_CLEAR,
	/*KOEI*/
	EVENT_KOEI_REPEAT_START,
	EVENT_KOEI_REPEAT_END,
	EVENT_KOEI_REPEAT_JUMP,
	/*Aisystem Tokyo*/
	EVENT_AISYSTEM_RESET_PROG,
	/*Kennosuke Suemura*/
	EVENT_KS_VOLUME,
	EVENT_KS_ASDR,
	EVENT_KS_FIR1,
	EVENT_KS_FIR2,
	EVENT_KS_LOOP_START,
	EVENT_KS_LOOP_END,
	EVENT_KS_VELOCITY0,
	EVENT_KS_VELOCITY1,
	EVENT_KS_VELOCITY2,
	EVENT_KS_VELOCITY3,
	EVENT_KS_VELOCITY4,
	EVENT_KS_VELOCITY5,
	EVENT_KS_VELOCITY6,
	EVENT_KS_VELOCITY7,
	EVENT_KS_VELOCITY8,
	EVENT_KS_VELOCITY9,
	EVENT_KS_VELOCITYA,
	EVENT_KS_VELOCITYB,
	EVENT_KS_VELOCITYC,
	EVENT_KS_VELOCITYD,
	EVENT_KS_VELOCITYE,
	EVENT_KS_VELOCITYF,
	EVENT_KS_ECHO_ON,
		EVENT_KS_ECHO_OFF,
		EVENT_KS_FIR_FILTER,
		EVENT_KS_END,
		/*Hect*/
		EVENT_HECT_SUB_COMMAND,
		/*Heart Beat*/
		EVENT_HB_SLUR_ON,
		EVENT_HB_SLUR_OFF,
		EVENT_HB_ECHO_VOLUME,
		EVENT_HB_ECHO_ON,
		EVENT_HB_ECHO_OFF,
		EVENT_HB_ECHO_FIR,
		EVENT_HB_ASDR,
		EVENT_HB_DUR_VEL,
		EVENT_HB_JUMP,
		EVENT_HB_CALL,
		EVENT_HB_RETURN,
		EVENT_HB_NOISE_ON,
		EVENT_HB_NOISE_OFF,
		EVENT_HB_NOISE_CLOCK,
		EVENT_HB_SUB_COMMAND,
		/*Quest*/
		EVENT_QUEST_APU_WRITE,
		EVENT_QUEST_PARAMETERS,
		EVENT_QUEST_CMD_VOICE,
		EVENT_QUEST_JUMP,
		EVENT_QUEST_ASDR_GAIN,
		EVENT_QUEST_PITCH,
		EVENT_QUEST_ASDR,
		EVENT_QUEST_LONG_NOTE,
		EVENT_QUEST_REPEAT_START,
		EVENT_QUEST_REPEAT_END,
		EVENT_QUEST_GAIN,
		EVENT_QUEST_ECHO_START_DELAY,
		EVENT_QUEST_SUB_COMMAND,
		/*Virgin*/
		EVENT_VIRGIN_NOTE_LEN,
		EVENT_VIRGIN_PAN_PARAM,
		EVENT_VIRGIN_VIBRATO_PARAM1,
		EVENT_VIRGIN_VIBRATO_PARAM2,
		EVENT_VIRGIN_VIBRATO_PARAM3,
		EVENT_VIRGIN_MASTER_VOLUME_PARAM,
		EVENT_VIRGIN_TEMPO_FADE_PARAM,
		EVENT_VIRGIN_VOLUME_FADE_PARAM,
		EVENT_VIRGIN_ECHO_VOLUME_PARAM1,
		EVENT_VIRGIN_ECHO_VOLUME_PARAM2,
		EVENT_VIRGIN_ECHO_PARAM1,
		EVENT_VIRGIN_ECHO_PARAM2,
		/*CP.BRAiN*/
		EVENT_CPBRAIN_SUB_COMMAND,
		/*Kyouhei Sada*/
		EVENT_SADA_ASDR,
		EVENT_SADA_PITCH,
		EVENT_SADA_ECHO1,
		EVENT_SADA_ECHO2,
		EVENT_SADA_ECHO3,
		EVENT_SADA_QUANTIZATION,
		EVENT_SADA_SLUR,
		EVENT_SADA_REST_REPEAT,
		EVENT_SADA_REPEAT_START,
		EVENT_SADA_REPEAT_END,
		/*Make Software*/
		EVENT_MAKE1_REPEAT_START,
		EVENT_MAKE1_REPEAT_END,
		EVENT_MAKE1_CALL,
		EVENT_MAKE1_RETURN,
		EVENT_MAKE1_SONG_LOOP,
		EVENT_MAKE1_SUB_COMMAND,
		EVENT_MAKE2_ASDR,
		EVENT_MAKE2_VOLUME_ADD,
		EVENT_MAKE2_TUNING2,
		EVENT_MAKE2_SPEED,
		EVENT_MAKE2_SUB_COMMAND,
		/*MIHO*/
		EVENT_MIHO_CALL,
		EVENT_MIHO_RETURN,
		EVENT_MIHO_REPEAT,
		/*MINT*/
		EVENT_MINT_VIBRATO,
		EVENT_MINT_ECHO_VOL,
		EVENT_MINT_CALL,
		EVENT_MINT_REPEAT_START,
		EVENT_MINT_REPEAT_END,
		EVENT_MINT_NOTE_ADD,
		EVENT_MINT_NOTE_ADD_TUNING,
		/*Sting*/
		EVENT_STING_CHAN_MASK,
		EVENT_STING_QUANTIZATION,
		EVENT_STING_VIBRATO,
		EVENT_STING_VOL_ENV1,
		EVENT_STING_VOL_ENV2,
		EVENT_STING_FADE_OUT,
		EVENT_STING_PITCH_SLIDE,
		EVENT_STING_SLUR_ON,
		EVENT_STING_SLUR_OFF,
		EVENT_STING_CALL,
		EVENT_STING_RETURN,
		EVENT_STING_REPEAT_START,
		EVENT_STING_REPEAT_END,
		EVENT_STING_ASDR1,
		EVENT_STING_ASDR2,
		EVENT_STING_GAIN,
		EVENT_STING_ASDR_GAIN,
		EVENT_STING_PITCH_ENV,
		EVENT_STING_PITCH,
		EVENT_STING_GET_SLUR,
		EVENT_STING_ECHO1,
		EVENT_STING_ECHO2,
		EVENT_STING_FIR,
		EVENT_STING_ECHO_VOL,
		EVENT_STING_ECHO_ON,
		EVENT_STING_ECHO_OFF,
		EVENT_STING_NOISE_OFF,
		EVENT_STING_PMOD,
		EVENT_STING_RESET_PITCH,
		EVENT_STING_NOTE_LEN,
		/*Betop (I'Max)*/
		EVENT_BETOP_CALL,
		EVENT_BETOP_RETURN,
		EVENT_BETOP_REPEAT_START,
		EVENT_BETOP_REPEAT_END,
		EVENT_BETOP_JUMP,
		EVENT_BETOP_QUANTIZE,
};

unsigned int STATUS_END;
unsigned int STATUS_NOTE_LEN_MIN;
unsigned int STATUS_NOTE_LEN_MAX;
unsigned int STATUS_NOTE_MIN;
unsigned int STATUS_NOTE_MAX;
unsigned int STATUS_PERCUSSION_NOTE_MIN;
unsigned int STATUS_PERCUSSION_NOTE_MAX;

unsigned int EventMap[256];